name: Merge upstream branches

# This action is mostly taken from this stackoverflow answer: https://stackoverflow.com/a/61574295/957317
on:
  schedule:
    # With '* * * * *' ~5 minutes is the highest effective frequency you will get
    # - cron: "0 8 * * *" # every day
    - cron: "*/30 * * * *" # every 30 minutes

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name 'Sam Spycher'
          git config --global user.email 'samspycher@users.noreply.github.com'

          # "git checkout master" is unnecessary, already here by default
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)

          git remote add upstream https://github.com/nightscout/AndroidAPS.git
          git fetch upstream

          # -b opt required because the omnipod_eros_dev ref is ambiguous at this stage
          git checkout -b dev origin/dev
          git merge --no-edit upstream/dev
          git push origin dev

          # use this syntax for the branch this action is running in (default)
          git checkout master 
          git merge --no-edit upstream/master
          git push origin master

          # other branches
